# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Data Preprocessing
Every data, that we wish to fed into a learning algorithm to learns the patterns and trends in it, must be frist cleaned and made ready for the algorithm to understand it.

In [2]:
#loading dataset

columns = ["id","diagnosis","radius_mean","texture_mean","perimeter_mean","area_mean","smoothness_mean","compactness_mean",
           "concavity_mean","concave points_mean","symmetry_mean","fractal_dimension_mean","radius_se","texture_se",
           "perimeter_se","area_se","smoothness_se","compactness_se","concavity_se","concave points_se","symmetry_se",
           "fractal_dimension_se","radius_worst","texture_worst","perimeter_worst","area_worst","smoothness_worst",
           "compactness_worst","concavity_worst","concave points_worst","symmetry_worst","fractal_dimension_worst",]
df = pd.read_csv("wdbc.csv",names = columns)
print(df.shape)
df.head(10)

(569, 32)


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   
5  ...         15.47          23.75           103.40       741.6   
6  ...         22.88          27.66           153.20      1606.0   
7  ...         17.06          28.14           110.60       897.0   
8  ...         15.49          30.73           106.20       739.3   
9  ...         15.09          40.68            97.65       711.4   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   
5            0.1791             0.5249           0.5355                0.1741   
6            0.1442             0.2576           0.3784                0.1932   
7            0.1654             0.3682           0.2678                0.1556   
8            0.1703             0.5401           0.5390                0.2060   
9            0.1853             1.0580           1.1050                0.2210   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  
5          0.3985                  0.12440  
6          0.3063                  0.08368  
7          0.3196                  0.11510  
8          0.4378                  0.10720  
9          0.4366                  0.20750  

[10 rows x 32 columns]

In [3]:
# droping id columns because it is not needed.
del df['id']
#checking for column with a empty cell i.e containing NA value
df.isna().any()

diagnosis                  False
radius_mean                False
texture_mean               False
perimeter_mean             False
area_mean                  False
smoothness_mean            False
compactness_mean           False
concavity_mean             False
concave points_mean        False
symmetry_mean              False
fractal_dimension_mean     False
radius_se                  False
texture_se                 False
perimeter_se               False
area_se                    False
smoothness_se              False
compactness_se             False
concavity_se               False
concave points_se          False
symmetry_se                False
fractal_dimension_se       False
radius_worst               False
texture_worst              False
perimeter_worst            False
area_worst                 False
smoothness_worst           False
compactness_worst          False
concavity_worst            False
concave points_worst       False
symmetry_worst             False
fractal_di

In [4]:
# checking total malignant(cancer) cells and benign(non-cancer) cells.
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [5]:
# changing categorical data into int numbers so that learning algorithms can understand them.
# the malignant representation "M" will be converted to 1 and benign representation to 0.
label_encoder = LabelEncoder()
df['diagnosis'] = label_encoder.fit_transform(df["diagnosis"].values)
df['diagnosis'].value_counts()

0    357
1    212
Name: diagnosis, dtype: int64

In [6]:
# now we will be spliting dataset into training and testing parts.
y = df.iloc[:,0].values
x = df.iloc[:,0:].values
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [7]:
# now we will feature scale the data. It is important so that all the valuse will have same weight for
# our learning algorithm.

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Model Building
Now that our data is ready to be fed in learning algorithms, we will proceed toward model building. We will be using many different classification algorithms and will see how each would preform on same data.


In [8]:
#Using Logistic Regression Algorithm to the Training Set

lr = LogisticRegression(random_state = 0)
lr.fit(X_train, Y_train)

#Using KNeighborsClassifier Method of neighbors class to use Nearest Neighbor algorithm

knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, Y_train)

#Using SVC method of svm class to use Support Vector Machine Algorithm

svm = SVC(kernel = 'linear', random_state = 0)
svm.fit(X_train, Y_train)

#Using GaussianNB method of naïve_bayes class to use Naïve Bayes Algorithm

gnb = GaussianNB()
gnb.fit(X_train, Y_train)

#Using DecisionTreeClassifier of tree class to use Decision Tree Algorithm

dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt.fit(X_train, Y_train)

#Using RandomForestClassifier method of ensemble class to use Random Forest Classification algorithm

rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [9]:
# now we will check accuracy of each model by testing them on X_test.
model = (lr,knn,svm,gnb,dt,rf)
models = ('lr','knn','svm','gnb','dt','rf')
for i in range(len((lr,knn,svm,gnb,dt,rf))):
    print("The accuracy of {} is {}".format(models[i],accuracy_score(Y_test, model[i].predict(X_test))))
    print()#Print a new line

The accuracy of lr is 1.0

The accuracy of knn is 0.986013986013986

The accuracy of svm is 1.0

The accuracy of gnb is 1.0

The accuracy of dt is 1.0

The accuracy of rf is 1.0



In [10]:
# now we will use confusion matrix to see how many times the models predicted accurately.
# the count of rightly predicted will be on the main diagnol of the matrix.
# the count of wrongly predicted will be on the other diagnol of the matrix.

for i in range(len(model)):
    cm = confusion_matrix(Y_test, model[i].predict(X_test))
 
    print(cm)
    print('{} Testing Accuracy = "{}!"'.format(models[i],  (cm[0][0] + cm[1][1]) / (cm[0][0] + cm[1][1] + cm[1][0] + cm[0][1])))
    print()# Print a new line

[[90  0]
 [ 0 53]]
lr Testing Accuracy = "1.0!"

[[90  0]
 [ 2 51]]
knn Testing Accuracy = "0.986013986013986!"

[[90  0]
 [ 0 53]]
svm Testing Accuracy = "1.0!"

[[90  0]
 [ 0 53]]
gnb Testing Accuracy = "1.0!"

[[90  0]
 [ 0 53]]
dt Testing Accuracy = "1.0!"

[[90  0]
 [ 0 53]]
rf Testing Accuracy = "1.0!"



In [11]:
for i in range(len(model)):
    pred = model[i].predict(X_test)
    print("{}".format(models[i]))
    unique, counts = np.unique(pred, return_counts=True)
    pred = dict(zip(unique, counts))
    print(pred)

    #Print a space
    print()

    #Print the actual values
    unique, counts = np.unique(Y_test, return_counts=True)
    Y_test_count = dict(zip(unique, counts))
    print(Y_test_count)

lr
{0: 90, 1: 53}

{0: 90, 1: 53}
knn
{0: 92, 1: 51}

{0: 90, 1: 53}
svm
{0: 90, 1: 53}

{0: 90, 1: 53}
gnb
{0: 90, 1: 53}

{0: 90, 1: 53}
dt
{0: 90, 1: 53}

{0: 90, 1: 53}
rf
{0: 90, 1: 53}

{0: 90, 1: 53}
